name: CD

on:
    push:
        branches:
            - master

jobs:
    release-please:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              id: release
              uses: GoogleCloudPlatform/release-please-action@v2.20.1
              with:
                  changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
                  release-type: node
                  package-name: test-gh-actions
    publish:
        name: Publish to NPM
        needs: release-please
        if: ${{ needs.release-please.steps.release.outputs.release_created }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.x
                  registry-url: https://registry.npmjs.org/
            - run: npm install --ignore-scripts
            - run: npm publish --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
