name: Check Markdown for Broken Links

on:
    push:
        paths:
            - "**/*.md"
    pull_request:
        paths:
            - "**/*.md"
    schedule:
        # 01:30 every day
        - cron: "30 1 * * *"
    # Allows this workflow to be run manually from the Actions tab
    workflow_dispatch:

jobs:
    link-check:
        name: Link Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - name: Run Linkinator
              run: npx linkinator '{,!(node_modules)/**/}*.md' --skip 'https://github.com/Fdawgs/.*/(commit|issues)/, http://0.0.0.0'
