name: Sigh

on:
    push:
        branches:
            - "release*"
    pull_request:
        branches:
            - "master"
            - "release*"
    # Allows this workflow to be run manually from the Actions tab
    workflow_dispatch:

jobs:
    format:
        name: Format files with Prettier
        #  if: github.actor == 'github-actions[bot]'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
              with:
                  refs: github.ref

            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14
            - run: echo "This PR is opened by ${{ github.event.pull_request.user.login }}  at  ${{ github.ref }}."
            - run: |
                  npm ci --ignore-scripts
                  npm run lint:prettier
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git remote add gh-token "https://${{ secrets.GITHUB_TOKEN}}@github.com/Fdawgs/test-gh-actions.git"
